const Footer = () => {
  return (
    <footer className="mt-16 pb-2 pt-6 text-neutral-500 text-sm border-t border-neutral-800 relative bottom-0">
      <div className="flex flex-col sm:flex-row sm:justify-between justify-start gap-6">
        <div className="text-sm">
          <p>Generated by Nicolás Demaria</p>
          <p className="mt-1">
            <a
              href="https://studio-building.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-white hover:text-neutral-300 font-medium transition-colors"
            >
              vruumvruum.studio
            </a>
          </p>
        </div>
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="text-sm">
            <a
              href="/about"
              className=" hover:text-neutral-300 font-medium transition-colors"
            >
              About
            </a>
          </div>
          <div className="text-sm">
            <a
              href="/pricing-policy"
              className=" hover:text-neutral-300 font-medium transition-colors"
            >
              Pricing Policy
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
