const Footer = () => {
  return (
    <footer className="text-center mt-16 py-6 text-neutral-500 text-sm border-t border-neutral-800">
      UX/UI Review generated by Nicolás Demaria | Confidential
      <p className="mt-1">
        <a
          href="https://studio-building.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-white hover:text-neutral-300 font-medium transition-colors"
        >
          vruumvruum.studio
        </a>
      </p>
    </footer>
  );
};

export default Footer;
