const Footer = () => {
  return (
    <footer className="mt-16 py-6 text-neutral-500 text-sm border-t border-neutral-800">
      <div className="container mx-auto flex justify-between items-center">
        <div className="text-sm">
          <p>Generated by Nicolás Demaria | Confidential</p>
          <p className="mt-1">
            <a
              href="https://studio-building.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-white hover:text-neutral-300 font-medium transition-colors"
            >
              vruumvruum.studio
            </a>
          </p>
        </div>
        <div className="text-sm">
          <a
            href="/pricing-policy"
            className=" hover:text-neutral-300 font-medium transition-colors"
          >
            Pricing Policy
          </a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
